### ISSUE TITLE
[Feat]: Build user profile page	

### ISSUE THREAD

**Issue by krshkun** [krshkun/LocaLink#1]
### Description

Add user profile page	

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshkun/localink/blob/main/CODE_OF_CONDUCT.md)

**Comment by drvcodenta** [comment]
How to get this issue?

**Comment by drvcodenta** [comment]
import Link from "next/link";
import * as React from 'react'
import Image from "next/image";
export default function UserProfile(){
  return (
    <div className="container">
    <div className="w-full h-[66.66vh] flex flex-col items-center justify-center space-y-8 p-4 xs:p-8 sm:p-12 md:p-16 lg:p-20 xl:p-24 2xl:p-28">
      <div className="row">
      <Image src={User.image} style={{ width: '100px', height: '100px',borderRadius:'50%'}} alt="User Profile-Image" />
      <h2 style={{color: "fff",textDecorationStyle: "solid"}}>{User.name}</h2>
      </div>
      <div className="row">
      <h3 style={{textDecorationStyle: "solid"}}>Followers:{User.followers}</h3>
      </div>
      <div className="row">
      <h3 style={{textDecorationStyle: "solid"}}>Following:{User.following}</h3>
      </div>
      <div className="row">
      <h3 style={{textDecorationStyle: "solid"}}>Posts:{User.posts}</h3>
      </div>
    </div>
    </div>
  )
}
